# Generated by Django 5.1.4 on 2025-01-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_user_avatar_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/%Y/%m/'),
        ),
    ]
