# Generated by Django 5.1.4 on 2025-01-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
