# Generated by Django 5.1.4 on 2025-01-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_class_department_user_student_class_class_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='tags',
        ),
    ]
