# Generated by Django 5.1.4 on 2025-01-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_remove_newsfeed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='proof',
            field=models.ImageField(blank=True, upload_to='reports/%Y/%m/'),
        ),
    ]
