# Generated by Django 5.1.4 on 2025-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_alter_report_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='proof',
            field=models.ImageField(upload_to='reports/%Y/%m/'),
        ),
    ]
