# Generated by Django 5.1.4 on 2025-01-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_alter_report_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinepoint',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scores.activity'),
            preserve_default=False,
        ),
    ]
