# Generated by Django 5.1.4 on 2025-01-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_disciplinepoint_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('max_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='disciplinepoint',
            old_name='total_score',
            new_name='group_total_score',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplinepoint',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplinepoint',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.evaluationcriteria'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.evaluationgroup'),
        ),
    ]
