# Generated by Django 5.1.4 on 2025-01-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='proof',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='proof',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='image',
        ),
    ]
