# Generated by Django 5.1.4 on 2025-01-27 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_rename_proof_participation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
