# Generated by Django 5.1.4 on 2025-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_newsfeed_description_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
