# Generated by Django 5.1.4 on 2025-01-27 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0016_message_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
