# Generated by Django 5.1.4 on 2025-02-02 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0017_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='disciplinepoint',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='evaluationgroup',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_form_response_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
