# Generated by Django 5.1.4 on 2025-02-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_alter_activity_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='google_form_response_id',
        ),
    ]
