# Generated by Django 5.1.4 on 2025-02-02 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0019_remove_registration_google_form_response_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 2, 3, 33, 17, 236268, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
