# Generated by Django 5.1.4 on 2025-02-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0021_evaluationcriteria_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/'),
        ),
    ]
